name: wordpress_local_${PROJECT_SUFFIX}

services:
  wordpress:
    container_name: wordpress_${PROJECT_SUFFIX}
    build: ./wordpress
    image: wordpress:6.8.1-php8.1-apache
    restart: no
    ports:
      - 80:80
      - 443:443
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_NAME: ${WP_DB_NAME}
      WORDPRESS_DB_USER: ${WP_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WP_DB_PASSWORD}
      WORDPRESS_DEBUG: ${WP_DEBUG}
    volumes:
      - wordpress_vol:/var/www/html
      - ./wordpress/apache/.htaccess:/var/www/html/.htaccess
      - ./wordpress/wp-config.php:/var/www/html/wp-config.php
      - ./wp-logs:/var/www/html/.apache
      - ./wp-plugins:/var/www/html/wp-content/plugins
      - ./wp-themes:/var/www/html/wp-content/themes
    depends_on:
      - mariadb
    mem_limit: 512m
    cpus: 0.5

  mariadb:
    container_name: mariadb_${PROJECT_SUFFIX}
    image: mariadb:11.4.5-noble
    restart: no
    volumes:
      - mariadb_vol:/var/lib/mysql
    environment:
      MARIADB_USER: ${WP_DB_USER}
      MARIADB_ROOT_PASSWORD: ${WP_DB_PASSWORD}
      MARIADB_DATABASE: ${WP_DB_NAME}
    mem_limit: 256m
    cpus: 0.3

  phpmyadmin:
    container_name: phpmyadmin_${PROJECT_SUFFIX}
    build: ./phpmyadmin
    restart: no
    ports:
      - ${PHPMYADMIN_PORT}:443
    volumes:
      - phpmyadmin_vol:/var/www/html
      - ./wordpress/apache/certs:/etc/apache2/ssl
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ${WP_DB_PASSWORD}
      UPLOAD_LIMIT: 1G
    depends_on:
      - mariadb
    mem_limit: 256m
    cpus: 0.3

volumes:
  phpmyadmin_vol:
  wordpress_vol:
  mariadb_vol:
